site_name: Vakyansh
nav:
      - Home: index.md
      - "User Guide":
              - "Data Collection Pipeine": "data_collection.md"
              - "Intelligent Data Pipeline": "intelligent_data_pipelines.md"
              - "Model Training Pipeline": "model_training.md"
      - About:
              - "License": LICENSE.md
              - "Contributions": CONTRIBUTING.md
              - "Release notes": RELEASE_NOTES.md
