site_name: Vakyansh
nav:
      - Home: index.md
      - "User Guide":
              - "Data Collection Pipeine": "data_collection.md"
              - "Intelligent Data Pipeline": "intelligent_data_pipelines.md"
              - "Model Training Pipeline": "model_training.md"
              - "Crowdsourcing Platform": "crowdsource_platform.md"
              - "Architecture Decision Records" : "adr.md"
                        - "Cache above RDBMS" : "adr_cache.md"
      - About:
              - "License": LICENSE
              - "Contributions": CONTRIBUTING.md
              - "Release notes": RELEASE_NOTES.md
