site_name: Vakyansh
nav:
      - Home: index.md
      - "User Guide":
              - "Smart Crawlers": "smart_crawlers.md"
              - "Intelligent Data Pipelines": "data_pipelines.md"
              - "Model Training Pipeline": "model_training.md"
      - About:
              - "License": LICENSE.md
              - "Contributions": CONTRIBUTING.md
              - "Release notes": RELEASE_NOTES.md
